name       : pdfpc
version    : 4.4.1
release    : 15
source     :
    - https://github.com/pdfpc/pdfpc/archive/v4.4.1.tar.gz : 4adb42fd1844a7e2ab44709dd043ade618c87f2aaec03db64f7ed659e8d3ddad
homepage   : https://pdfpc.github.io/
license    : GPL-2.0-or-later
component  : office.viewers
summary    : A presenter console with multi-monitor support for PDF files
description: |
    pdfpc is a GTK based presentation viewer application which uses Keynote like multi-monitor output to provide meta information to the speaker during the presentation. It is able to show a normal presentation window on one screen, while showing a more sophisticated overview on the other one providing information like a picture of the next slide, as well as the left over time till the end of the presentation.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(poppler-glib)
    - extra-cmake-modules
    - vala
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
